
(()=>{
 const SUPA_URL='https://ridrrcprspixtrbwygeo.supabase.co', SUPA_KEY='sb_publishable_qPkd-UXm7X2KRA-E5a00jA_O8Ya4iSr';
 const qs=new URLSearchParams(location.search), invited=(qs.get('to')||'').replace(/\+/g,' ').trim();
 const db=window.supabase?window.supabase.createClient(SUPA_URL,SUPA_KEY,{auth:{persistSession:false,autoRefreshToken:false}}):null;

 // ---------- Event Day / After Wedding automatic modes (WITA = UTC+8) ----------
 const now=Date.now(), eventStart=Date.parse('2027-02-06T16:00:00Z'), eventEnd=Date.parse('2027-02-07T16:00:00Z');
 const eventHero=document.getElementById('eventDayHero'), afterHero=document.getElementById('afterWeddingHero');
 if(now>=eventStart && now<eventEnd){document.body.classList.add('event-day');if(eventHero)eventHero.hidden=false}
 else if(now>=eventEnd){document.body.classList.add('after-wedding');if(afterHero)afterHero.hidden=false;const nav=document.getElementById('miniNav');if(nav&&!nav.querySelector('a[href="#closing"]')){const a=document.createElement('a');a.href='#closing';a.innerHTML='<span>♡</span><small>Penutup</small>';a.setAttribute('aria-label','Penutup');nav.appendChild(a)}}

 // ---------- Optional live streaming ----------
 const stream=document.getElementById('livestream');
 window.ZAActivateStream=(rawUrl)=>{const streamUrl=String(rawUrl||'').trim();if(!streamUrl||!stream)return false;let safeUrl='';try{const u=new URL(streamUrl);if(!/^https?:$/.test(u.protocol))return false;safeUrl=u.href}catch(e){return false}stream.classList.add('stream-ready');const screen=document.getElementById('streamScreen'),open=document.getElementById('streamOpen');let embed='';try{const u=new URL(safeUrl);if(/(^|\.)youtube\.com$|(^|\.)youtu\.be$/.test(u.hostname)){let id=u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).pop();if(id)embed='https://www.youtube.com/embed/'+encodeURIComponent(id)}}catch(e){}if(embed&&screen)screen.innerHTML='<iframe src="'+embed+'" title="Live Streaming Zaky & Agnes" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe>';else if(screen)screen.innerHTML='<div class="stream-placeholder"><strong>Live Streaming</strong><span>Tekan tombol di bawah untuk membuka siaran.</span></div>';if(open){open.href=safeUrl;open.hidden=false}return true};
 const fallbackStreamUrl=(document.querySelector('meta[name="za-stream-url"]')?.content||'').trim();if(fallbackStreamUrl)window.ZAActivateStream(fallbackStreamUrl);

 // ---------- Offline status pill ----------
 const pill=document.createElement('div');pill.className='offline-pill';pill.textContent='Mode offline · data akan disinkronkan';document.body.appendChild(pill);const net=()=>pill.classList.toggle('show',!navigator.onLine);addEventListener('online',net);addEventListener('offline',net);net();

 // ---------- Text submission outbox ----------
 const OUTBOX='za-premium-outbox-v2';
 const getOutbox=()=>{try{return JSON.parse(localStorage.getItem(OUTBOX)||'[]')}catch(e){return[]}};
 const setOutbox=v=>{try{localStorage.setItem(OUTBOX,JSON.stringify(v.slice(-120)))}catch(e){}};
 window.ZAQueueSubmission=item=>{const q=getOutbox();q.push({...item,id:crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random(),at:Date.now()});setOutbox(q)};
 async function flushOutbox(){if(!navigator.onLine||!db)return;const q=getOutbox(), keep=[];for(const item of q){try{if(item.type==='wish'){const payload={...item.payload,status:'pending'};const{error}=await db.from('wishes').insert([payload]);if(error)throw error}else if(item.type==='rsvp'){let{error}=await db.from('rsvps').insert([item.payload]);if(error&&/phone|checkin_code|column/i.test(String(error.message||''))){const {phone,checkin_code,...legacy}=item.payload;({error}=await db.from('rsvps').insert([legacy]))}if(error)throw error}else if(item.type==='analytics'){const{error}=await db.from('invitation_events').insert([item.payload]);if(error)throw error}else keep.push(item)}catch(e){keep.push(item)}}setOutbox(keep)}
 addEventListener('online',()=>setTimeout(flushOutbox,800));setTimeout(flushOutbox,1800);

 // ---------- Privacy-friendly analytics (no name/phone stored) ----------
 const sessionKey='za-session-id-v2';let sessionId=localStorage.getItem(sessionKey);if(!sessionId){sessionId=crypto.randomUUID?crypto.randomUUID():'s-'+Date.now().toString(36)+Math.random().toString(36).slice(2);try{localStorage.setItem(sessionKey,sessionId)}catch(e){}}
 async function hashGuest(v){if(!v||!crypto.subtle)return null;try{const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v.toLowerCase()));return [...new Uint8Array(b)].slice(0,12).map(x=>x.toString(16).padStart(2,'0')).join('')}catch(e){return null}}
 let guestHashPromise=hashGuest(invited);
 async function track(event_type,meta={}){if(!db)return;const payload={event_type,session_id:sessionId,guest_hash:await guestHashPromise,path:location.pathname,meta};try{const{error}=await db.from('invitation_events').insert([payload]);if(error)throw error}catch(e){window.ZAQueueSubmission?.({type:'analytics',payload})}}
 setTimeout(()=>track('page_view',{mode:document.body.classList.contains('event-day')?'event-day':document.body.classList.contains('after-wedding')?'after-wedding':'normal'}),900);
 document.addEventListener('click',e=>{const t=e.target.closest('a,button,.slide');if(!t)return;if(t.matches('#openInvitation'))track('invitation_open');else if(t.matches('#routeFromMe,.location-actions a'))track('maps_click');else if(t.matches('#proShareTop,#shareInvite'))track('share_click');else if(t.matches('#downloadCalendar,.calendar-action'))track('calendar_click');else if(t.matches('#receiptPassBtn,#passShare'))track('wedding_pass');else if(t.matches('#gallery .slide'))track('gallery_open');else if(t.matches('#streamOpen'))track('stream_click')},{passive:true});

 // ---------- Guest Photo Drop + IndexedDB offline queue ----------
 const photoName=document.getElementById('guestPhotoName'),photoFiles=document.getElementById('guestPhotoFiles'),photoBtn=document.getElementById('guestPhotoUpload'),photoStatus=document.getElementById('guestPhotoStatus'),photoPreview=document.getElementById('guestPhotoPreview');
 if(photoName&&invited)photoName.value=invited;let selected=[];
 function previewFiles(){photoPreview.innerHTML='';selected.slice(0,3).forEach(f=>{const img=document.createElement('img');img.src=URL.createObjectURL(f);img.onload=()=>URL.revokeObjectURL(img.src);photoPreview.appendChild(img)});photoPreview.classList.toggle('show',selected.length>0)}
 photoFiles?.addEventListener('change',()=>{selected=[...photoFiles.files].slice(0,3);previewFiles();photoStatus.textContent=selected.length?selected.length+' foto siap dikirim.':''});
 function compress(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{try{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),hh=Math.max(1,Math.round(img.height*scale)),c=document.createElement('canvas');c.width=w;c.height=hh;c.getContext('2d',{alpha:false}).drawImage(img,0,0,w,hh);c.toBlob(b=>{URL.revokeObjectURL(url);b?resolve(b):reject(new Error('compress'))},'image/webp',.82)}catch(e){URL.revokeObjectURL(url);reject(e)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('image'))};img.src=url})}
 const PDB='za-photo-outbox-v1';function openPDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(PDB,1);r.onupgradeneeded=()=>r.result.createObjectStore('tasks',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
 async function savePhotoTask(task){const d=await openPDB();await new Promise((res,rej)=>{const tx=d.transaction('tasks','readwrite');tx.objectStore('tasks').put(task);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});d.close()}
 async function getPhotoTasks(){const d=await openPDB();const out=await new Promise((res,rej)=>{const r=d.transaction('tasks').objectStore('tasks').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)});d.close();return out}
 async function deletePhotoTask(id){const d=await openPDB();await new Promise((res,rej)=>{const tx=d.transaction('tasks','readwrite');tx.objectStore('tasks').delete(id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});d.close()}
 async function uploadPhotoTask(task){if(!db)throw new Error('supabase');const ext=task.blob.type.includes('webp')?'webp':'jpg',path='guest/'+new Date().toISOString().slice(0,10)+'/'+task.id+'.'+ext;let{error}=await db.storage.from('guest-photos').upload(path,task.blob,{contentType:task.blob.type||'image/webp',upsert:false});if(error)throw error;({error}=await db.from('guest_photos').insert([{guest_name:task.name||'Tamu',invited_to:task.invited_to||null,storage_path:path,status:'pending'}]));if(error)throw error;return path}
 async function flushPhotoTasks(){if(!navigator.onLine||!db)return;for(const t of await getPhotoTasks()){try{await uploadPhotoTask(t);await deletePhotoTask(t.id)}catch(e){}}}
 addEventListener('online',()=>setTimeout(flushPhotoTasks,1200));setTimeout(flushPhotoTasks,2400);
 photoBtn?.addEventListener('click',async()=>{const name=(photoName.value||invited||'Tamu').trim(),consent=document.getElementById('guestPhotoConsent');if(!consent?.checked){photoStatus.textContent='Centang persetujuan penyimpanan foto terlebih dahulu 🤍';return}let last=0;try{last=Number(localStorage.getItem('za-photo-last-submit')||0)}catch(e){}if(Date.now()-last<20000){photoStatus.textContent='Tunggu sebentar sebelum mengirim foto lagi 🤍';return}if(!selected.length){photoStatus.textContent='Pilih minimal satu foto terlebih dahulu 🤍';return}photoBtn.disabled=true;photoStatus.textContent='Menyiapkan foto…';let sent=0,queued=0;try{for(const f of selected){if(!/^image\//.test(f.type))continue;const blob=await compress(f),task={id:crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2),blob,name,invited_to:invited||null,created_at:Date.now()};if(navigator.onLine&&db){try{await uploadPhotoTask(task);sent++}catch(e){await savePhotoTask(task);queued++}}else{await savePhotoTask(task);queued++}}selected=[];photoFiles.value='';previewFiles();photoStatus.textContent=sent&&queued?sent+' foto terkirim, '+queued+' menunggu koneksi.':queued?'📶 Foto disimpan di perangkat dan akan diunggah saat internet kembali.':sent+' foto berhasil dikirim untuk album kenangan 🤍';try{localStorage.setItem('za-photo-last-submit',String(Date.now()))}catch(_e){};track('guest_photo_upload',{sent,queued})}catch(e){photoStatus.textContent='Foto belum dapat diproses. Coba pilih foto lain.'}finally{photoBtn.disabled=false}});
})();
