
(()=>{
 const SUPA_URL='https://ridrrcprspixtrbwygeo.supabase.co',SUPA_KEY='sb_publishable_qPkd-UXm7X2KRA-E5a00jA_O8Ya4iSr';
 const udb=window.supabase?window.supabase.createClient(SUPA_URL,SUPA_KEY,{auth:{persistSession:false,autoRefreshToken:false}}):null;
 const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
 let sid='';try{sid=localStorage.getItem('za-session-id-v2')||''}catch(e){}if(!sid){sid=(crypto.randomUUID?crypto.randomUUID():'s-'+Date.now()+Math.random());try{localStorage.setItem('za-session-id-v2',sid)}catch(e){}}
 // Honeypots for basic bot filtering.
 const addHP=(host,id)=>{if(!host||document.getElementById(id))return;const i=document.createElement('input');i.id=id;i.name='website';i.tabIndex=-1;i.autocomplete='off';i.setAttribute('aria-hidden','true');i.style.cssText='position:absolute!important;left:-9999px!important;width:1px!important;height:1px!important;opacity:0!important';host.appendChild(i)};addHP(q('#rsvpForm'),'zaRsvpWebsite');addHP(q('#wishP'),'zaWishWebsite');
 // Utility panel.
 const panel=q('#ultimatePanel'),fab=q('#ultimateFab');const openPanel=v=>{panel.hidden=!v;fab.setAttribute('aria-expanded',String(v))};fab?.addEventListener('click',()=>openPanel(panel.hidden));q('#ultimateClose')?.addEventListener('click',()=>openPanel(false));document.addEventListener('click',e=>{if(!panel?.hidden&&!q('#ultimateUi')?.contains(e.target))openPanel(false)});
 const state={lang:localStorage.getItem('za-lang')||'id',font:localStorage.getItem('za-font-large')==='1',motion:localStorage.getItem('za-reduce-motion')==='1',contrast:localStorage.getItem('za-contrast')==='1',low:localStorage.getItem('za-low-data')==='1'};
 function cls(){document.body.classList.toggle('za-font-large',state.font);document.body.classList.toggle('za-reduce-motion',state.motion);document.body.classList.toggle('za-contrast',state.contrast);document.body.classList.toggle('za-low-data',state.low);q('#fontToggle')?.classList.toggle('on',state.font);q('#motionToggle')?.classList.toggle('on',state.motion);q('#contrastToggle')?.classList.toggle('on',state.contrast);q('#lowDataToggle')?.classList.toggle('on',state.low)}cls();
 q('#fontToggle')?.addEventListener('click',()=>{state.font=!state.font;localStorage.setItem('za-font-large',state.font?'1':'0');cls()});q('#motionToggle')?.addEventListener('click',()=>{state.motion=!state.motion;localStorage.setItem('za-reduce-motion',state.motion?'1':'0');cls()});q('#contrastToggle')?.addEventListener('click',()=>{state.contrast=!state.contrast;localStorage.setItem('za-contrast',state.contrast?'1':'0');cls()});q('#lowDataToggle')?.addEventListener('click',()=>{state.low=!state.low;localStorage.setItem('za-low-data',state.low?'1':'0');cls();setupMap(true)});
 // Bahasa Indonesia / English for the primary guest-facing UI.
 const T={
  '#openInvitation':['Buka Undangan','Open Invitation'],'.guest-honor':['Kepada Yth. Bapak/Ibu/Saudara/i','To Our Honored Guest'],'.guest-sub':['Dengan hormat, kami mengundang Anda untuk hadir di hari bahagia kami.','With heartfelt joy, we invite you to be part of our wedding celebration.'],
  '#rsvp .script':['Kehadiran & Doa Restu','RSVP & Warm Wishes'],'#rsvpP .submit':['Kirim RSVP','Send RSVP'],'#editRsvpLast':['Ubah RSVP Terakhir','Edit Last RSVP'],'#wishSubmit':['Kirim Ucapan','Send Wish'],
  '#guestphotos .script':['Kirim Foto Untuk Kami','Share Your Photos'],'#guestphotos .lead':['Punya foto atau momen favorit bersama kami? Kirimkan di sini untuk menjadi bagian dari album kenangan Zaky & Agnes.','Have a favorite photo or memory with us? Share it here to become part of Zaky & Agnes’s wedding album.'],'#guestPhotoUpload':['Kirim Foto Kenangan','Send Memory Photos'],'#faq .script':['FAQ & Kontak','FAQ & Contact'],
  '#count .count-title':['Menuju Janji Suci','Counting Down to Our Promise'],'#rundown .script':['Rangkaian Hari Bahagia','Our Wedding Timeline'],'#rundown .lead':['Dengan penuh sukacita, berikut rangkaian momen yang akan kami rayakan bersama.','With joyful hearts, here is the sequence of moments we will celebrate together.'],
  '#gift .lead':['Kehadiran dan doa restu Anda merupakan anugerah terindah bagi kami. Apabila berkenan menyampaikan tanda kasih, kami menerimanya dengan penuh rasa syukur.','Your presence and warm wishes are the greatest gift to us. If you would like to send a token of love, we receive it with heartfelt gratitude.'],
  '#closing .lead':['Terima kasih telah menjadi bagian dari perjalanan kami. Kehadiran dan doa restu Bapak/Ibu/Saudara/i akan menjadi kenangan indah dalam hari bahagia kami.','Thank you for being part of our journey. Your presence and warm wishes will remain a beautiful memory from our special day.'],
  '#faq details:nth-of-type(1) summary':['Di mana lokasi acara?','Where is the venue?'],'#faq details:nth-of-type(2) summary':['Apakah saya perlu RSVP?','Do I need to RSVP?'],'#faq details:nth-of-type(3) summary':['Bagaimana jika sinyal di lokasi kurang baik?','What if the venue has poor signal?'],'#faq details:nth-of-type(4) summary':['Bagaimana cara mengirim foto?','How do I share photos?'],
  '#backTop':['↑ Kembali ke Atas','↑ Back to Top']
 };
 function setLang(lang){state.lang=lang;localStorage.setItem('za-lang',lang);document.documentElement.lang=lang;qa('[data-lang]').forEach(b=>b.classList.toggle('on',b.dataset.lang===lang));Object.entries(T).forEach(([sel,vals])=>{const el=q(sel);if(el){if(!el.dataset.zaOrig)el.dataset.zaOrig=el.textContent;el.textContent=lang==='en'?vals[1]:vals[0]}});const navMap={Waktu:'Time',Kami:'Couple',Acara:'Event',Rundown:'Timeline',Story:'Story',Galeri:'Gallery',Hadiah:'Gift',RSVP:'RSVP'};qa('#miniNav small').forEach(el=>{const id=el.dataset.zaId||el.textContent.trim();el.dataset.zaId=id;el.textContent=lang==='en'?(navMap[id]||id):id});const labels=qa('#rsvpForm label');if(labels[0])labels[0].childNodes[0].nodeValue=lang==='en'?'Name':'Nama';if(labels[1])labels[1].childNodes[0].nodeValue=lang==='en'?'Attendance':'Kehadiran';if(labels[2])labels[2].childNodes[0].nodeValue=lang==='en'?'WhatsApp Number ':'Nomor WhatsApp ';if(labels[3])labels[3].childNodes[0].nodeValue=lang==='en'?'Number of Guests':'Jumlah Tamu';const sel=q('#rsvpForm select[name=attendance]');if(sel){sel.options[0].text=lang==='en'?'Choose one':'Pilih salah satu';sel.options[1].text=lang==='en'?'Yes, I will attend':'InsyaAllah hadir';sel.options[2].text=lang==='en'?'Sorry, I cannot attend':'Mohon maaf, tidak dapat hadir'}q('#contactHelperText')&&(q('#contactHelperText').textContent=lang==='en'?'Family WhatsApp contacts can be configured from Wedding Admin.':'Nomor WhatsApp keluarga dapat ditampilkan di sini setelah dikonfigurasi melalui Wedding Admin.');
  const nameInput=q('#rsvpForm [name=name]'),phoneInput=q('#rsvpForm [name=phone]'),wishName=q('#wishName'),wishMsg=q('#wishMessage'),photoName=q('#guestPhotoName');
  if(nameInput)nameInput.placeholder=lang==='en'?'Your name':'Isi nama';if(phoneInput)phoneInput.placeholder=lang==='en'?'Example: 081234567890':'Contoh: 081234567890';if(wishName)wishName.placeholder=lang==='en'?'Your name':'Isi nama';if(wishMsg)wishMsg.placeholder=lang==='en'?'Write your warm wishes':'Tulis ucapan terbaik kamu';if(photoName)photoName.placeholder=lang==='en'?'Photo sender name':'Nama pengirim';
  const faqP=qa('#faq details p'),enFaq=['The ceremony and reception will be held at Gas Alam Badak 1, Muara Badak, East Kalimantan. Use the Google Maps button in Event & Location.','Yes. RSVP helps us prepare for your arrival. An RSVP sent from this device can be updated later.','The invitation supports offline/PWA mode. Save or install it on your phone before leaving so important information remains accessible.','Open Guest Photo Drop, choose up to three photos, accept the storage consent, and send them. Photos enter moderation and are not published automatically.'];const idFaq=['Akad dan resepsi dilaksanakan di Gas Alam Badak 1, Muara Badak, Kalimantan Timur. Gunakan tombol Google Maps pada bagian Acara & Lokasi.','Ya. RSVP membantu kami menyiapkan penerimaan tamu dengan lebih baik. RSVP yang sudah dikirim dapat diperbarui kembali dari perangkat yang sama.','Undangan memiliki mode offline/PWA. Simpan atau pasang undangan di HP sebelum berangkat agar informasi penting tetap mudah diakses.','Buka bagian Guest Photo Drop, pilih maksimal tiga foto, setujui izin penyimpanan, lalu kirim. Foto masuk ke tahap kurasi dan tidak langsung tampil ke publik.'];faqP.forEach((x,i)=>x.textContent=(lang==='en'?enFaq:idFaq)[i]||x.textContent);
 }
 qa('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));setLang(state.lang);
 // Print/PDF + native sharing.
 q('#printInvite')?.addEventListener('click',()=>window.print());q('#shareInviteUltimate')?.addEventListener('click',async()=>{const data={title:'The Wedding of Zaky & Agnes',text:(window.ZA_EVENT_DATE_SHORT||'7 Februari 2027')+' · '+(window.ZA_MAP_DEST||'Gas Alam Badak 1, Muara Badak'),url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);alert('Link undangan disalin 🤍')}}catch(e){}});
 // Lazy map / Low Data mode.
 const mapFrame=q('#events .venue-map iframe');function loadMap(){if(mapFrame&&!mapFrame.src&&mapFrame.dataset.src)mapFrame.src=mapFrame.dataset.src}function setupMap(force=false){if(!mapFrame)return;let ph=q('.map-load-placeholder');if(state.low){if(mapFrame.src&&mapFrame.src!=='about:blank'){mapFrame.removeAttribute('src')}if(!ph){ph=document.createElement('div');ph.className='map-load-placeholder';ph.innerHTML='<div><p class="low-data-map-note">Low Data aktif. Peta dimuat hanya jika Anda memilihnya.</p><button type="button">Muat Peta</button></div>';mapFrame.parentElement.appendChild(ph);ph.querySelector('button').addEventListener('click',()=>{state.low=false;localStorage.setItem('za-low-data','0');cls();ph.remove();loadMap()})}}else{ph?.remove();if(force)loadMap();else if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>{if(es.some(x=>x.isIntersecting)){loadMap();io.disconnect()}},{rootMargin:'250px'});io.observe(mapFrame)}else loadMap()}}setupMap();
 // Public-safe settings, maintenance redirect, announcement, and family contacts.
 const wa=v=>String(v||'').replace(/\D/g,'').replace(/^0/,'62');
 const MEDIA_SLOTS={media_zaky:'--zsolo',media_agnes:'--asolo',media_p0:'--p0',media_p1:'--p1',media_p2:'--p2',media_p3:'--p3',media_p4:'--p4'};
 const VALID_THEMES=['black-cherry-bloom','champagne','black-gold','ivory-pearl','emerald-gold','royal-navy','burgundy-romance','sage-botanical','rose-gold','terracotta-rustic','celestial-night','marble-gold','editorial-mono'];
 const THEME_COLORS={'black-cherry-bloom':'#8e2d3b',champagne:'#eadbd4','black-gold':'#17130d','ivory-pearl':'#f0eadf','emerald-gold':'#10291e','royal-navy':'#10243d','burgundy-romance':'#3a121d','sage-botanical':'#dce6d8','rose-gold':'#ead3da','terracotta-rustic':'#e4c9b8','celestial-night':'#171d40','marble-gold':'#e4e3df','editorial-mono':'#dad9d5'};
 function applySiteTheme(v){const theme=VALID_THEMES.includes(String(v||''))?String(v):'black-cherry-bloom',root=document.documentElement;root.dataset.theme=theme;if(theme==='black-cherry-bloom'){root.dataset.fontStyle='black-cherry';root.style.setProperty('--theme-accent','#8E2D3B','important');root.style.setProperty('--theme-accent2','#A07A80','important');root.style.setProperty('--theme-heading','#3A0E1E','important');root.style.setProperty('--theme-text','#3A0E1E','important');root.style.setProperty('--theme-muted','#A07A80','important')}else{root.style.removeProperty('--theme-accent');root.style.removeProperty('--theme-accent2');root.style.removeProperty('--theme-heading');root.style.removeProperty('--theme-text');root.style.removeProperty('--theme-muted')}try{localStorage.setItem('za-site-theme',theme)}catch(_e){}const meta=document.querySelector('meta[name=theme-color]');if(meta)meta.content=THEME_COLORS[theme]||'#8e2d3b';}
 try{const cached=localStorage.getItem('za-site-theme');if(VALID_THEMES.includes(cached))applySiteTheme(cached)}catch(_e){}
 const validMedia=v=>typeof v==='string'&&(v.startsWith('data:image/')||/^https:\/\//i.test(v));
 function applyMediaOverrides(x={}){
  const root=document.documentElement;
  Object.entries(MEDIA_SLOTS).forEach(([key,cssVar])=>{const url=x[key];if(validMedia(url))root.style.setProperty(cssVar,`url("${url.replace(/"/g,'%22')}")`)});
  const p=[x.media_p0,x.media_p1,x.media_p2,x.media_p3,x.media_p4];
  // Story uses p2, p1, p3, p4 in that order; Gallery uses p0..p4.
  [2,1,3,4].forEach((slot,i)=>{const img=qa('#story img')[i];if(img&&validMedia(p[slot]))img.src=p[slot]});

  qa('#gallery .slide img').forEach((img,i)=>{if(validMedia(p[i]))img.src=p[i]});
  [0,2,4].forEach((slot,i)=>{const img=qa('#cinematic img[data-default-var]')[i];if(img&&validMedia(p[slot]))img.src=p[slot]});
  window.ZAEnsureEmbeddedPhotos?.();
 }
 const ZA_DEFAULT_CONTENT={couple:{groom_full:'Muhammad Zaky Khairy',groom_short:'Zaky',groom_parents:'Putra dari Bapak Tiar Saputra & Ibu Murni',bride_full:'Agnes Viannisa',bride_short:'Agnes',bride_parents:'Putri dari Bapak Sugeng Purwanto & Ibu Linawati, S.pd.'},event:{date:'2027-02-07',akad_time:'08:00',reception_time:'11:00',end_time:'23:59',venue_name:'Gas Alam Badak 1',venue_area:'Muara Badak, Kalimantan Timur',maps_query:'Gas Alam Badak 1, Muara Badak, Kalimantan Timur',maps_url:'',max_guests:10,rsvp_deadline:''},text:{opening:'Dengan hormat, kami mengundang Anda untuk hadir di hari bahagia kami.',guest_template:'Dengan hormat, kami mengundang {nama} untuk hadir di hari bahagia kami.',closing:'Terima kasih telah menjadi bagian dari perjalanan kami. Kehadiran dan doa restu Bapak/Ibu/Saudara/i akan menjadi kenangan indah dalam hari bahagia kami.',gift_lead:'Kehadiran dan doa restu Anda merupakan anugerah terindah bagi kami. Apabila berkenan menyampaikan tanda kasih, kami menerimanya dengan penuh rasa syukur.'},story:[],gifts:[],display:{font_style:'black-cherry',animation_mode:'cinematic',animation_speed:1,accent:'#8e2d3b',wishes:true,wedding_pass:true,gift_confirm:true,sections:{},section_order:[]}};
 function zaMerge(a,b){a=JSON.parse(JSON.stringify(a));if(!b||typeof b!=='object')return a;const walk=(x,y)=>{Object.keys(y).forEach(k=>{if(y[k]&&typeof y[k]==='object'&&!Array.isArray(y[k])&&x[k]&&typeof x[k]==='object'&&!Array.isArray(x[k]))walk(x[k],y[k]);else x[k]=y[k]});return x};return walk(a,b)}
 const zaEsc=s=>String(s??'');
 const pad2=n=>String(n).padStart(2,'0');
 function zaDateInfo(date){try{const d=new Date(date+'T12:00:00+08:00'),full=new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Makassar'}).format(d),short=new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Makassar'}).format(d);return {full:full.charAt(0).toUpperCase()+full.slice(1),short:short.charAt(0).toUpperCase()+short.slice(1),compact:new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'Asia/Makassar'}).format(d).replace(/\//g,' · ')}}catch(e){return{full:date,short:date,compact:date}}}
 function zaTime(t){return String(t||'').replace(':','.')}
 function zaSetText(sel,v){const el=q(sel);if(el&&v!=null)el.textContent=v}
 function zaEventText(card,date,time,venue){const p=card?.querySelector('p');if(!p)return;p.textContent='';p.append(document.createTextNode(date),document.createElement('br'));const b=document.createElement('b');b.textContent=zaTime(time)+' WITA – selesai';p.append(b,document.createElement('br'),document.createTextNode(venue+'.'))}
 function zaApplySections(d){const site=q('.site');const sections=d.sections||{};Object.entries(sections).forEach(([id,on])=>{const el=document.getElementById(id);if(el)el.style.display=on===false?'none':''});const order=Array.isArray(d.section_order)?d.section_order:[];if(site&&order.length)order.forEach(id=>{const el=document.getElementById(id);if(el&&el.parentElement===site)site.appendChild(el)});qa('#miniNav a[href^="#"]').forEach(a=>{const id=(a.getAttribute('href')||'').slice(1),el=document.getElementById(id);a.style.display=el&&el.style.display==='none'?'none':''})}
 function zaApplyGifts(c){const cards=qa('#gift .bank-card'),gifts=Array.isArray(c.gifts)?c.gifts:[];cards.forEach((card,i)=>{const g=gifts[i];if(!g)return;card.style.display=g.enabled===false?'none':'';zaSetText('#gift .bank-card:nth-of-type('+(i+1)+') .bank-name',g.bank);zaSetText('#gift .bank-card:nth-of-type('+(i+1)+') .bank-no',g.number);zaSetText('#gift .bank-card:nth-of-type('+(i+1)+') .bank-owner','a.n. '+g.holder);const b=card.querySelector('[data-copy]');if(b)b.dataset.copy=g.number||''});const sel=q('#giftConfirmBank');if(sel){sel.innerHTML='<option value="">Pilih rekening</option>';gifts.filter(g=>g&&g.enabled!==false&&g.number).forEach(g=>{const o=document.createElement('option');o.value=(g.bank||'Bank')+' - '+(g.holder||'');o.textContent=(g.bank||'Bank')+' · '+(g.holder||'');sel.appendChild(o)})}}
 function zaRenderCalendar(date){const cal=q('#count .calendar-4d');if(!cal||!date)return;try{const [y,m,d]=date.split('-').map(Number),monthName=new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric',timeZone:'Asia/Makassar'}).format(new Date(Date.UTC(y,m-1,15))),head=cal.querySelector('.cal-head span:nth-child(2)'),days=cal.querySelector('.cal-days');if(head)head.textContent=monthName.charAt(0).toUpperCase()+monthName.slice(1);cal.setAttribute('aria-label','Kalender '+monthName);if(days){days.innerHTML='';const first=new Date(Date.UTC(y,m-1,1)).getUTCDay(),offset=(first+6)%7,total=new Date(Date.UTC(y,m,0)).getUTCDate();for(let i=0;i<offset;i++){const x=document.createElement('div');x.className='cal-day empty';x.setAttribute('aria-hidden','true');days.appendChild(x)}for(let n=1;n<=total;n++){const x=document.createElement('div');x.className='cal-day'+(n===d?' wedding':'');x.textContent=n;days.appendChild(x)}}}catch(e){}}
 function zaApplyDisplay(d){const root=document.documentElement,body=document.body,isCherry=root.dataset.theme==='black-cherry-bloom';root.dataset.fontStyle=isCherry?'black-cherry':(d.font_style||'luxury');body.dataset.adminMotion=d.animation_mode||'cinematic';root.style.setProperty('--za-admin-speed',String(Number(d.animation_speed)||1));if(isCherry){root.style.setProperty('--theme-accent','#8E2D3B','important');root.style.setProperty('--theme-accent2','#A07A80','important');root.style.setProperty('--theme-heading','#3A0E1E','important');root.style.setProperty('--theme-text','#3A0E1E','important');root.style.setProperty('--theme-muted','#A07A80','important')}else if(/^#[0-9a-f]{6}$/i.test(String(d.accent||''))){root.style.setProperty('--theme-accent',d.accent)}zaApplySections(d);const wishTab=q('#rsvp .tab[data-tab="wishP"]'),wishPanel=q('#wishP');if(wishTab)wishTab.style.display=d.wishes===false?'none':'';if(wishPanel&&d.wishes===false)wishPanel.style.display='none';const passBtn=q('#receiptPassBtn');if(passBtn)passBtn.style.display=d.wedding_pass===false?'none':'';const gc=q('#gift .gift-confirm');if(gc)gc.style.display=d.gift_confirm===false?'none':''}
 function applyUltimateContent(raw,musicUrl,musicTitle){const c=zaMerge(ZA_DEFAULT_CONTENT,(raw&&typeof raw==='object')?raw:{}),cp=c.couple||{},ev=c.event||{},tx=c.text||{},di=c.display||{},dt=zaDateInfo(ev.date||'2027-02-07'),shortPair=(cp.groom_short||'Zaky')+' & '+(cp.bride_short||'Agnes'),venue=[ev.venue_name,ev.venue_area].filter(Boolean).join(', '),mapsQuery=ev.maps_query||venue;
  window.ZA_EVENT_DATE=ev.date||'2027-02-07';window.ZA_EVENT_DATE_SHORT=dt.short;window.ZA_COUPLE_SHORT=shortPair;window.ZA_VENUE_AREA=ev.venue_area||'';window.ZA_MAP_DEST=mapsQuery;
  window.ZA_DYNAMIC_CONTENT=c;zaRenderCalendar(ev.date);
  const eventIso=(ev.date||'2027-02-07')+'T'+(ev.akad_time||'08:00')+':00+08:00';window.ZASetCountdownTarget?.(eventIso);
  zaSetText('#opening .open-names',shortPair);zaSetText('#opening .open-date',dt.short);zaSetText('#postOpenHero .post-open-names',shortPair);zaSetText('#postOpenHero .post-open-date',dt.full.replace(',',' ·'));zaSetText('#count .count-date',dt.short);zaSetText('#zaky h3',cp.groom_full);zaSetText('#zaky .profile-copy p',cp.groom_parents);zaSetText('#agnes h3',cp.bride_full);zaSetText('#agnes .profile-copy p',cp.bride_parents);zaSetText('#book .script',shortPair);const bn=qa('#book .book-name');if(bn[0])bn[0].textContent=cp.groom_short||'Zaky';if(bn[1])bn[1].textContent=cp.bride_short||'Agnes';zaSetText('#closing .close-name',shortPair);zaSetText('#closing .close-date',dt.short);zaSetText('#closing .lead',tx.closing);zaSetText('#closing .closing-final-mark small',(dt.short+' · '+(ev.venue_area||'')).toUpperCase());zaSetText('.pass-top .pass-label span',dt.short);zaSetText('#opening .guest-sub',String(tx.guest_template||tx.opening||'').replaceAll('{nama}',window.ZA_PERSONAL_GUEST_NAME||q('#guestName')?.textContent||'Tamu Undangan'));zaSetText('#gift .lead',tx.gift_lead);
  const cine=q('#cinematic .cine-caption span');if(cine)cine.textContent=dt.compact;const cc=q('#cinematic .cine-caption');if(cc&&cc.firstChild&&cc.firstChild.nodeType===3)cc.firstChild.nodeValue=shortPair+' ';
  const eventCards=qa('#events .event-card');zaEventText(eventCards[0],dt.full,ev.akad_time,venue);zaEventText(eventCards[1],dt.full,ev.reception_time,venue);
  zaSetText('#events .loc-head h3',ev.venue_name);const lp=q('#events .loc-head p');if(lp){lp.textContent='';lp.append(document.createTextNode(ev.venue_area||''),document.createElement('br'),document.createTextNode('Lihat lokasi acara langsung pada peta di bawah ini.'))}const pin=q('#events .venue-pin-float');if(pin){const st=pin.querySelector('strong');if(st)st.textContent=ev.venue_name;pin.lastChild&&pin.lastChild.nodeType===3&&(pin.lastChild.nodeValue=ev.venue_area||'')}
  const frame=q('#events .venue-map iframe'),embed='https://www.google.com/maps?q='+encodeURIComponent(mapsQuery)+'&output=embed';if(frame){frame.dataset.src=embed;if(frame.src&&frame.src!=='about:blank')frame.src=embed;frame.title='Peta '+(ev.venue_name||'lokasi acara')}const mapLink=q('#events .location-actions a.primary');if(mapLink)mapLink.href=ev.maps_url||('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(mapsQuery));const faqLoc=q('#faq details:first-of-type p');if(faqLoc)faqLoc.textContent='Akad dan resepsi dilaksanakan di '+venue+'. Gunakan tombol Google Maps pada bagian Acara & Lokasi.';
  const rt=qa('#rundown .rundown-time');if(rt[0])rt[0].textContent=zaTime(ev.akad_time);if(rt[1])rt[1].textContent=zaTime(ev.reception_time);const last=qa('#rundown .rundown-card span').at(-1);if(last)last.textContent='Acara berlangsung hingga selesai di '+venue+'.';
  const story=Array.isArray(c.story)?c.story:[];qa('#story .timeline article').forEach((a,i)=>{const s=story[i];if(!s)return;const h=a.querySelector('h3'),p=a.querySelector('p');if(h)h.textContent=s.title||'';if(p)p.textContent=s.text||''});zaApplyGifts(c);
  const siteMax=Math.max(1,Math.min(50,Number(ev.max_guests)||10)),max=window.ZA_PERSONAL_GUEST_TOKEN?Math.min(siteMax,Math.max(1,Number(window.ZA_PERSONAL_GUEST_QUOTA)||1)):siteMax,gi=q('#rsvpForm [name="guests"]');if(gi){gi.max=String(max);if(Number(gi.value)>max)gi.value=String(max)}if(ev.rsvp_deadline){const deadline=Date.parse(ev.rsvp_deadline+(/Z$|[+-]\d\d:?\d\d$/.test(ev.rsvp_deadline)?'':'+08:00'));if(Number.isFinite(deadline)&&Date.now()>deadline){const submit=q('#rsvpP .submit');if(submit){submit.disabled=true;submit.textContent='RSVP Sudah Ditutup'}const note=q('#rsvpStatus');if(note)note.textContent='Batas waktu RSVP telah berakhir. Hubungi keluarga jika ada perubahan kehadiran.'}}
  const cal=q('#count .calendar-action');if(cal){const start=(ev.date||'').replaceAll('-','')+'T'+String(ev.akad_time||'08:00').replace(':','')+'00',end=(ev.date||'').replaceAll('-','')+'T'+String(ev.end_time||'23:59').replace(':','')+'00';cal.href='https://calendar.google.com/calendar/render?action=TEMPLATE&text='+encodeURIComponent('Pernikahan '+shortPair)+'&dates='+start+'/'+end+'&ctz=Asia%2FMakassar&location='+encodeURIComponent(venue);const sm=cal.querySelector('small');if(sm)sm.textContent=dt.full}
  const mus=q('#music');if(mus&&musicUrl){const was=!mus.paused;mus.src=String(musicUrl);mus.load();if(was)mus.play().catch(()=>{})}const mb=q('#musicBtn');if(mb&&musicTitle)mb.title=String(musicTitle);
  zaApplyDisplay(di);
  document.title='The Wedding of '+shortPair+' — '+dt.short;const md=document.querySelector('meta[name="description"]');if(md)md.content='Undangan pernikahan '+(cp.groom_full||'')+' & '+(cp.bride_full||'')+' — '+dt.short;const og=document.querySelector('meta[property="og:description"]');if(og)og.content=dt.full+' · '+venue;
  // Re-evaluate event-day / after-wedding mode from admin date.
  const startDay=Date.parse((ev.date||'2027-02-07')+'T00:00:00+08:00'),endDay=Date.parse((ev.date||'2027-02-07')+'T23:59:59+08:00');if(Number.isFinite(startDay)){document.body.classList.toggle('event-day',Date.now()>=startDay&&Date.now()<=endDay);document.body.classList.toggle('after-wedding',Date.now()>endDay);const eh=q('#eventDayHero'),ah=q('#afterWeddingHero');if(eh)eh.hidden=!(Date.now()>=startDay&&Date.now()<=endDay);if(ah)ah.hidden=!(Date.now()>endDay)}
 }
 async function loadSettings(){
  if(!udb)return;
  try{
   const{data,error}=await udb.rpc('get_public_wedding_settings');
   if(error)throw error;
   let rows=Array.isArray(data)?data:[];
   const mediaKeys=['media_zaky','media_agnes','media_p0','media_p1','media_p2','media_p3','media_p4'];
   const fallbackKeys=[...mediaKeys,'site_theme','site_content','music_url','music_title'];
   // Compatibility fallback for older public-settings RPC versions.
   if(!rows.some(r=>r?.setting_key==='site_theme')||!rows.some(r=>mediaKeys.includes(r?.setting_key))){
    try{
     const{data:mr}=await udb.from('wedding_site_settings').select('key,value').in('key',fallbackKeys);
     if(Array.isArray(mr)){const seen=new Set(rows.map(r=>r?.setting_key));rows=rows.concat(mr.filter(r=>!seen.has(r.key)).map(r=>({setting_key:r.key,setting_value:r.value}))) }
    }catch(_e){}
   }
   const x={};rows.forEach(r=>{if(r&&r.setting_key)x[r.setting_key]=r.setting_value});
   applySiteTheme(x.site_theme||'black-cherry-bloom');
   applyMediaOverrides(x);
   applyUltimateContent(x.site_content,x.music_url,x.music_title);
   const maintenance=x.maintenance_mode===true||x.maintenance_enabled===true;
   if(maintenance&&new URLSearchParams(location.search).get('preview')!=='1'){
    location.replace('./maintenance.html');return;
   }
   if(x.event_day_mode===true){document.body.classList.add('event-day');document.body.classList.remove('after-wedding');if(q('#eventDayHero'))q('#eventDayHero').hidden=false}
   if(x.after_wedding_mode===true){document.body.classList.add('after-wedding');document.body.classList.remove('event-day');if(q('#afterWeddingHero'))q('#afterWeddingHero').hidden=false}
   const annObj=x.public_announcement;const ann=String((annObj&&typeof annObj==='object')?(annObj.enabled===false?'':annObj.message||''):(x.announcement||'')).trim();
   if(ann){const a=q('#ultimateAnnouncement');a.textContent=ann;a.hidden=false}
   const actions=q('#familyContactActions');
   if(actions){
    actions.innerHTML='';
    const fw=(x.family_whatsapp&&typeof x.family_whatsapp==='object')?x.family_whatsapp:null;
    const contacts=[['Zaky',x.contact_zaky],['Agnes',x.contact_agnes],['Keluarga',x.contact_family||((fw&&fw.enabled!==false)?fw.number:'')]];
    contacts.forEach(([label,n])=>{const num=wa(n);if(!num)return;const a=document.createElement('a');a.target='_blank';a.rel='noopener';a.href='https://wa.me/'+num;a.textContent='WhatsApp '+label;actions.appendChild(a)});
    if(actions.children.length){q('#contactHelperText').textContent=state.lang==='en'?'Contact us through one of the WhatsApp buttons.':'Hubungi kami melalui salah satu tombol WhatsApp berikut.'}
   }
   const liveUrl=String(x.live_stream_url||x.stream_url||'').trim();if(liveUrl)window.ZAActivateStream?.(liveUrl);
  }catch(e){}
 }
 loadSettings();
 // Flush moderated wish and editable RSVP outboxes when connection returns.
 async function flushUltimate(){if(!navigator.onLine||!udb)return;try{const w=JSON.parse(localStorage.getItem('za-ultimate-wish-outbox')||'[]'),keep=[];for(const item of w){try{const{data:allowed,error:rateError}=await udb.rpc('allow_wedding_submission',{p_session_id:sid,p_event_kind:'wish',p_limit:4,p_window_seconds:600});if(rateError||!allowed){keep.push(item);continue}const{error}=await udb.from('wishes').insert([{name:item.name,message:item.message,status:'pending'}]);if(error)keep.push(item)}catch(_e){keep.push(item)}}localStorage.setItem('za-ultimate-wish-outbox',JSON.stringify(keep))}catch(e){}try{const r=JSON.parse(localStorage.getItem('za-ultimate-rsvp-outbox')||'null');if(r){const{data:allowed,error:rateError}=await udb.rpc('allow_wedding_submission',{p_session_id:r.sid||sid,p_event_kind:'rsvp',p_limit:6,p_window_seconds:600});if(!rateError&&allowed){const{data,error}=await udb.rpc('submit_or_update_rsvp',{p_edit_token:r.edit_token||null,p_name:r.name,p_attendance:r.attendance,p_guests:r.guests,p_phone:r.phone||null,p_invited_to:r.invited_to||null});if(!error&&data){const row=Array.isArray(data)?data[0]:data;const k='za-rsvp-edit-token-v1-'+((r.invited_to||'device').toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,70));if(row?.edit_token)localStorage.setItem(k,row.edit_token);localStorage.removeItem('za-ultimate-rsvp-outbox')}}}}catch(e){}}addEventListener('online',()=>setTimeout(flushUltimate,1000));setTimeout(flushUltimate,2200);
})();
